project_id = "yzwqiejnskxhmfdlnfkb"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.check-in-ticket]
verify_jwt = false

[functions.get-order-by-session]
verify_jwt = false

[functions.send-vendor-confirmation]
verify_jwt = false